### ISSUE TITLE
Enhanced to pass the Acid2Test and optional standard repeat range

### ISSUE THREAD

**Issue by sdsnatcher** [mvac7/Z80_RLEWB#1]
I made some enhancements to the unRLEWBtoVRAM.asm file. I hope it helps!

- Enhanced to pass the Acid2Test (IOW, MA-20 support)
- Added a DEFINE to allow to select wether the extended repeat range (2 to 255) or standard repeat range (1 to 254) will be used, in order to allow for compatibility with the [existing compressors](https://github.com/ericb59/rlewb-Compressor).

[unRLEWBtoVRAM.asm.gz](https://github.com/mvac7/Z80_RLEWB/files/4364620/unRLEWBtoVRAM.asm.gz)

**Comment by sdsnatcher** [comment]
I noticed I made a mistake on the previous version, so here's the fixed version with a small optimisation too.

[unRLEWBtoVRAM.asm.gz](https://github.com/mvac7/Z80_RLEWB/files/4377457/unRLEWBtoVRAM.asm.gz)

**Comment by mvac7** [comment]
@sdsnatcher 
I have uploaded your improvements, but I had to create another source for asMSX since this compiler did not work. 
Now there will be a specific source for asMSX and another for SjASM.
Thank you for your collaboration! :)

**Comment by sdsnatcher** [comment]
Maybe it's enough to just add a comment in the file header like this?

"To compile on asMSX, comment the lines that start with DEFINE, IFDEF and ENDIF".
